<a href="https://colab.research.google.com/github/Kavyakandhakatla/BDA_ICP1/blob/main/ICP3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

a. Using NumPy create random vector of size 15 having only Integers in the range 1-20.
1. 3. Reshape the array to 3 by 5
2. Print array shape.
Replace the max in each row by 0

In [ ]:
import numpy as np

In [ ]:
arr = np.random.randint(1, 21, size=15)
print("Initial array:", arr)
arr_reshaped = arr.reshape(3, 5)
print("Reshaped array to 3 by 5:", arr_reshaped)
print("Shape of array:", arr_reshaped.shape)
for i in range(arr_reshaped.shape[0]):
    index = np.argmax(arr_reshaped[i])
    arr_reshaped[i, index] = 0

print("Array after replacing max in each row with 0:", arr_reshaped)


Initial array: [ 3 18  2  9  8 10  7  6 17 16 15 12  1  2 20]
Reshaped array to 3 by 5: [[ 3 18  2  9  8]
 [10  7  6 17 16]
 [15 12  1  2 20]]
Shape of array: (3, 5)
Array after replacing max in each row with 0: [[ 3  0  2  9  8]
 [10  7  6  0 16]
 [15 12  1  2  0]]


 Create a 2-dimensional array of size 4 x 3 (composed of 4-byte integer elements), also print the shape, type and data
type of the array.

In [ ]:
arr = np.array([[0, 1, 2],
                [3, 4, 5],
                [6, 7, 8],
                [9, 10, 11]], dtype=np.int32)
print("Initial array:", arr)
print("Shape of the array:", arr.shape)
print("Type of the array:", type(arr))
print("Data type of elements in the array:", arr.dtype)


Initial array: [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Shape of the array: (4, 3)
Type of the array: <class 'numpy.ndarray'>
Data type of elements in the array: int32


Write a program to compute the eigenvalues and right eigenvectors of a given square array given below:
[[ 3 -2]
[ 1 0]]

In [ ]:
Array = np.array([[3, -2],
              [1,  0]])
eigenvalues, eigenvectors = np.linalg.eig(Array)
print("Eigenvalues:", eigenvalues)
print("Right Eigenvectors:", eigenvectors)


Eigenvalues: [2. 1.]
Right Eigenvectors: [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


 Compute the sum of the diagonal element of a given array.
[[0 1 2]
[3 4 5]]

In [ ]:
Array = np.array([[0, 1, 2],
              [3, 4, 5]])
sum = np.trace(Array)
print("Sum of diagonal elements:", sum)


Sum of diagonal elements: 4


Write a NumPy program to create a new shape to an array without changing its data.
Reshape 3x2:
[[1 2]
[3 4]
[5 6]]
Reshape 2x3:
[[1 2 3]
[4 5 6]]

In [ ]:
arr = np.array([[1, 2],
                [3, 4],
                [5, 6]])
print("Original array:", arr)
reshapeArray = arr.reshape(2, 3)
print("Reshaped arraty:", reshapeArray)


Original array: [[1 2]
 [3 4]
 [5 6]]
Reshaped arraty: [[1 2 3]
 [4 5 6]]


https://drive.google.com/file/d/1nrSwHCFdAn4g6Xd_OCOckQ-4lu_YCu2g/view?usp=drive_link